apiVersion: v2
name: kyverno-policies
icon: https://repository-images.githubusercontent.com/169108858/35923880-823a-11e9-9089-0c9c102f9e6f
description: A Weaveworks Helm chart for the Kyverno Profile
type: application
version: 0.0.3-0
dependencies:
- name: kyverno-policies
  version: "v2.1.3"
  repository: "https://kyverno.github.io/kyverno/"
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://kyverno.github.io/kyverno/

keywords:
- security
- kyverno
- kyverno-policies
- policies

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": kyverno-policies
  "weave.works/category": Deployment
  "weave.works/layer": layer-1
  "weave.works/links": |
    - name: Chart Sources
      url:  https://kyverno.github.io/kyverno/
    - name: Upstream Project
      url: https://github.com/kyverno/kyverno
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
