apiVersion: v2
name: prometheus
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
description: A Weaveworks Helm chart for observability
type: application
version: 0.0.8
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus

keywords:
- operator
- prometheus
- kube-prometheus
- observability

annotations:
  "weave.works/profile": prometheus
  "weave.works/category": Observability
  "weave.works/operator": "true"
  "weave.works/layer": layer-1
  "weave.works/links": |
    - name: Chart Sources
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus
  "weave.works/profile-ci": |
    - "gke"
    - "kind"

maintainers:
  - name: Weaveworks
    email: support@weave.works

dependencies:
- name: kube-prometheus-stack
  version: "19.2.2"
  repository: "https://prometheus-community.github.io/helm-charts"
  condition: kube-prometheus-stack.enabled
