aws-load-balancer-controller:
  enabled: true
  clusterName: ClusterName
  serviceAccount:
    # rbac.serviceAccount.annotations -- Additional Service Account annotations.
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::123456789012:role/MyRoleName'
aws-ebs-csi-driver:
  enabled: false
aws-node-termination-handler:
  enabled: true
