aws-load-balancer-controller:
  clusterName: ClusterName
  serviceAccount:
    # rbac.serviceAccount.annotations -- Additional Service Account annotations.
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::123456789012:role/MyRoleName'
aws-ebs-csi-driver:
  controller:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: 'arn:aws:iam::123456789012:role/MyRoleName'
