apiVersion: v2
name: magalix-agent
icon: https://www.magalix.com/hubfs/Imported%20images/logo-02.png%3Fwidth=560%26name=logo-02-Dec-18-2020-11-24-41-75-AM.png
description: A Weaveworks Helm chart for Magalix policy agent
type: application
version: 0.0.12
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://github.com/MagalixCorp/magalix-agent

keywords:
- magalix
- policy

maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": magalix
  "weave.works/category": Policy
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Upstream Project
      url: https://github.com/MagalixCorp/magalix-agent
