name: GKE Integration Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  gke-e2e-profile-test:
    name: gke e2e profile test
    runs-on: ubuntu-latest
    env:
      SSH_DIR: "~/.ssh"
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      GITHUB_TOKEN: ${{secrets.WEAVEWORKSBOT_PROFILES_CATALOG_RELEASE_TOKEN}}
      GIT_SSH_COMMAND: /tmp/ssh_command
      GIT_SSH_COMMAND_DEBUGLOG: "/tmp/1"
      TEST_REPO: profiles-catalog-test
      INFRASTRUCTURE: gke
      PIPELINE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Setup SSH known hosts
        shell: bash
        run: |
          mkdir -p ${SSH_DIR} && chmod 700 ${SSH_DIR}
          ssh-keyscan github.com >> ${SSH_DIR}/known_hosts
      - name: Install Go for profile e2e
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Run mgmt integration tests
        shell: bash
        env:
          PROFILE: gitops-enterprise-mgmt-gke
          GKE_CLUSTER_NAME: profiles-test-mgmt-${{ github.head_ref }}-${{ github.run_number }}
          TEST_REPO_BRANCH: e2e-gke-mgmt-${{ github.head_ref }}-${{ github.run_number }}
        run: |
          mkdir -p /tmp/git-keys
          echo "${{ secrets.PROFILES_CATALOG_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog 
          echo "${{ secrets.PROFILES_CATALOG_TEST_DEPLOY_KEY_2 }}" > /tmp/git-keys/weaveworks-profiles-catalog-test
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog-test
          echo "${{ secrets.PROFILES_CATALOG_TEST_DEPLOY_KEY_PUB_2 }}" > /tmp/git-keys/weaveworks-profiles-catalog-test.pub
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog-test.pub
          cp ${{ github.workspace }}/.bin/ssh_command.sh /tmp/ssh_command
          chmod +x /tmp/ssh_command
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          make gke-e2e || make delete-cluster && exit 1
      - name: Run leaf integration tests
        shell: bash
        env:
          PROFILE: gitops-enterprise-leaf-gke
          GKE_CLUSTER_NAME: profiles-test-leaf-${{ github.head_ref }}-${{ github.run_number }}
          TEST_REPO_BRANCH: e2e-gke-leaf-${{ github.head_ref }}-${{ github.run_number }}
        run: |
          mkdir -p /tmp/git-keys
          echo "${{ secrets.PROFILES_CATALOG_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog 
          echo "${{ secrets.PROFILES_CATALOG_TEST_DEPLOY_KEY_2 }}" > /tmp/git-keys/weaveworks-profiles-catalog-test
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog-test
          echo "${{ secrets.PROFILES_CATALOG_TEST_DEPLOY_KEY_PUB_2 }}" > /tmp/git-keys/weaveworks-profiles-catalog-test.pub
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog-test.pub
          cp ${{ github.workspace }}/.bin/ssh_command.sh /tmp/ssh_command
          chmod +x /tmp/ssh_command
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          make gke-e2e || make delete-cluster && exit 1
