name: Profile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kind-profile-test:
    name: Kind profile test
    runs-on: ubuntu-latest
    env:
      SSH_DIR: "~/.ssh"
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH known hosts
        shell: bash
        run: |
          mkdir -p ${SSH_DIR} && chmod 700 ${SSH_DIR}
          ssh-keyscan github.com >> ${SSH_DIR}/known_hosts
      - name: Run integration tests
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GIT_TOKEN: ${{secrets.GIT_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
          GIT_SSH_COMMAND: /tmp/ssh_command
          GIT_SSH_COMMAND_DEBUGLOG: "1"
        run: |
          mkdir -p /tmp/git-keys
          echo "${{ secrets.TESTING_CATALOG_PRIVATE_KIND_WEAVEWORKS_BOT_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog 
          echo "${{ secrets.TESTING_CATALOG_PRIVATE_KIND_WEAVEWORKS_BOT_DEPLOY_KEY }}" > /tmp/git-keys/ww-customer-test-profile-test-repo-kind 
          chmod 600 /tmp/git-keys/ww-customer-test-profile-test-repo-kind
          cp ${{ github.workspace }}/.bin/ssh_command.sh /tmp/ssh_command
          chmod +x /tmp/ssh_command
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          make kind
  eks-e2e-profile-test:
    name: EKS e2e profile test
    runs-on: ubuntu-latest
    env:
      SSH_DIR: "~/.ssh"
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Setup SSH known hosts
        shell: bash
        run: |
          mkdir -p ${SSH_DIR} && chmod 700 ${SSH_DIR}
          ssh-keyscan github.com >> ${SSH_DIR}/known_hosts
      - name: Run integration tests
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GIT_TOKEN: ${{secrets.GIT_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}
          GIT_SSH_COMMAND: /tmp/ssh_command
          GIT_SSH_COMMAND_DEBUGLOG: "1"
          KUBECONFIG: "/home/runner/work/profiles-catalog/profiles-catalog/.conf/profiles-cluster.kubeconfig"
          PROFILE: gitops-enterprise-mgmt-eks
          TEST_REPO: profile-test-repo-eks
          
        run: |
          mkdir -p /tmp/git-keys
          echo "${{ secrets.PROFILES_CATALOG_PRIVATE_WEAVEWORKS_BOT_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog 
          echo "${{ secrets.TESTING_CATALOG_PRIVATE_EKS_WEAVEWORKS_BOT_DEPLOY_KEY }}" > /tmp/git-keys/ww-customer-test-profile-test-repo-eks
          chmod 600 /tmp/git-keys/ww-customer-test-profile-test-repo-eks
          cp ${{ github.workspace }}/.bin/ssh_command.sh /tmp/ssh_command
          chmod +x /tmp/ssh_command
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          make eks-e2e