name: Profile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kind-e2e-profile-test:
    name: Kind e2e profile test
    runs-on: ubuntu-latest
    env:
      SSH_DIR: "~/.ssh"
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH known hosts
        shell: bash
        run: |
          mkdir -p ${SSH_DIR} && chmod 700 ${SSH_DIR}
          ssh-keyscan github.com >> ${SSH_DIR}/known_hosts
      - name: Run mgmt integration tests
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GITHUB_TOKEN: ${{secrets.WEAVEWORKSBOT_PROFILES_CATALOG_RELEASE_TOKEN}}
          GIT_SSH_COMMAND: /tmp/ssh_command
          GIT_SSH_COMMAND_DEBUGLOG: "/tmp/1"
          PROFILE: gitops-enterprise-mgmt-kind
          TEST_REPO: profiles-catalog-test
        run: |
          mkdir -p /tmp/git-keys
          echo "${{ secrets.PROFILES_CATALOG_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog 
          echo "${{ secrets.PROFILES_CATALOG_TEST_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog-test
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog-test
          cp ${{ github.workspace }}/.bin/ssh_command.sh /tmp/ssh_command
          chmod +x /tmp/ssh_command
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          make kind-e2e
      - name: Run leaf integration tests
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GITHUB_TOKEN: ${{secrets.WEAVEWORKSBOT_PROFILES_CATALOG_RELEASE_TOKEN}}
          GIT_SSH_COMMAND: /tmp/ssh_command
          GIT_SSH_COMMAND_DEBUGLOG: "/tmp/1"
          PROFILE: gitops-enterprise-leaf-kind
          TEST_REPO: profiles-catalog-test  
        run: |
          mkdir -p /tmp/git-keys
          echo "${{ secrets.PROFILES_CATALOG_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog 
          echo "${{ secrets.PROFILES_CATALOG_TEST_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog-test
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog-test
          cp ${{ github.workspace }}/.bin/ssh_command.sh /tmp/ssh_command
          chmod +x /tmp/ssh_command
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          make kind-e2e
      - name: Install Go for profile e2e
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Test profile e2e
        run: make test-single-profile
  eks-e2e-profile-test:
    name: EKS e2e profile test
    runs-on: ubuntu-latest
    env:
      SSH_DIR: "~/.ssh"
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Setup SSH known hosts
        shell: bash
        run: |
          mkdir -p ${SSH_DIR} && chmod 700 ${SSH_DIR}
          ssh-keyscan github.com >> ${SSH_DIR}/known_hosts
      - name: Run mgmt integration tests
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GITHUB_TOKEN: ${{secrets.WEAVEWORKSBOT_PROFILES_CATALOG_RELEASE_TOKEN}}
          GIT_SSH_COMMAND: /tmp/ssh_command
          GIT_SSH_COMMAND_DEBUGLOG: "/tmp/1"
          KUBECONFIG: "/home/runner/work/profiles-catalog/profiles-catalog/.conf/profiles-cluster.kubeconfig"
          PROFILE: gitops-enterprise-mgmt-eks
          TEST_REPO: profiles-catalog-test       
        run: |
          mkdir -p /tmp/git-keys
          echo "${{ secrets.PROFILES_CATALOG_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog 
          echo "${{ secrets.PROFILES_CATALOG_TEST_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog-test
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog-test
          cp ${{ github.workspace }}/.bin/ssh_command.sh /tmp/ssh_command
          chmod +x /tmp/ssh_command
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          make eks-e2e
      - name: Run leaf integration tests
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GITHUB_TOKEN: ${{secrets.WEAVEWORKSBOT_PROFILES_CATALOG_RELEASE_TOKEN}}
          GIT_SSH_COMMAND: /tmp/ssh_command
          GIT_SSH_COMMAND_DEBUGLOG: "/tmp/1"
          KUBECONFIG: "/home/runner/work/profiles-catalog/profiles-catalog/.conf/profiles-cluster.kubeconfig"
          PROFILE: gitops-enterprise-leaf-eks
          TEST_REPO: profiles-catalog-test       
        run: |
          mkdir -p /tmp/git-keys
          echo "${{ secrets.PROFILES_CATALOG_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog 
          echo "${{ secrets.PROFILES_CATALOG_TEST_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog-test
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog-test
          cp ${{ github.workspace }}/.bin/ssh_command.sh /tmp/ssh_command
          chmod +x /tmp/ssh_command
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          make eks-e2e
  gke-e2e-profile-test:
    name: gke e2e profile test
    runs-on: ubuntu-latest
    env:
      SSH_DIR: "~/.ssh"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Setup SSH known hosts
        shell: bash
        run: |
          mkdir -p ${SSH_DIR} && chmod 700 ${SSH_DIR}
          ssh-keyscan github.com >> ${SSH_DIR}/known_hosts
      - name: Run mgmt integration tests
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GITHUB_TOKEN: ${{secrets.WEAVEWORKSBOT_PROFILES_CATALOG_RELEASE_TOKEN}}
          GIT_SSH_COMMAND: /tmp/ssh_command
          GIT_SSH_COMMAND_DEBUGLOG: "/tmp/1"
          PROFILE: gitops-enterprise-mgmt-gke
          TEST_REPO: profiles-catalog-test       
        run: |
          mkdir -p /tmp/git-keys
          echo "${{ secrets.PROFILES_CATALOG_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog 
          echo "${{ secrets.PROFILES_CATALOG_TEST_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog-test
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog-test
          cp ${{ github.workspace }}/.bin/ssh_command.sh /tmp/ssh_command
          chmod +x /tmp/ssh_command
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          make gke-e2e
      - name: Run leaf integration tests
        shell: bash
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          GITHUB_TOKEN: ${{secrets.WEAVEWORKSBOT_PROFILES_CATALOG_RELEASE_TOKEN}}
          GIT_SSH_COMMAND: /tmp/ssh_command
          GIT_SSH_COMMAND_DEBUGLOG: "/tmp/1"
          PROFILE: gitops-enterprise-leaf-gke
          TEST_REPO: profiles-catalog-test       
        run: |
          mkdir -p /tmp/git-keys
          echo "${{ secrets.PROFILES_CATALOG_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog 
          echo "${{ secrets.PROFILES_CATALOG_TEST_DEPLOY_KEY }}" > /tmp/git-keys/weaveworks-profiles-catalog-test
          chmod 600 /tmp/git-keys/weaveworks-profiles-catalog-test
          cp ${{ github.workspace }}/.bin/ssh_command.sh /tmp/ssh_command
          chmod +x /tmp/ssh_command
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          make gke-e2e
